---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: 625011733915.dkr.ecr.ap-northeast-1.amazonaws.com/springclouddemo/api-gateway:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        name: api-gateway
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "100m"
        command: ["/bin/sh","-c"]
        args: ["/springCloud/env.sh"]
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
            - name: app-properties
              mountPath: /springCloud/conf/application.properties
              subPath: application.properties
              readOnly: true
      volumes:
        - name: app-properties
          secret:
            secretName: api-gateway
            items:
            - key: application.properties
              path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  name: api-gateway
  namespace: default
  labels:
    app: api-gateway
spec:
  ports:
    - port: 80
      name: server
      targetPort: 8081
  selector:
    app: api-gateway
  type: LoadBalancer